import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Allura as Cursive } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navigation from "@/components/Navigation";
import AppBar from "@/components/AppBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const cursive = Cursive({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cursive",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          cursive.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation loggedIn={false} />
          {children}
          <AppBar />
        </ThemeProvider>
      </body>
    </html>
  );
}
